### ISSUE TITLE
Badly named executable

### ISSUE THREAD

**Issue by jtgd** [maximbaz/dmenu-term#1]
You should have named your program "dmenu-term" or something instead of "dmenu". You wipe out the existing dmenu program on installation. It seems you did not think that the two programs could coexist on the same system. It may be a "drop in replacement" in some ways but it is not fully a replacement. It would be nice to have a functional equivalent to dmenu that runs in a terminal, but that certainly does not replace all the use cases for dmenu. Perhaps you don't understand how people use dmenu.

Also, it's buggy.

tail: cannot open '/tmp/tmp.0qG7EIPJRU/out' for reading: No such file or directory

**Comment by jtgd** [comment]
In trying to uninstall it I could not simply do "yay -Rns dmenu-term" because there are many dependencies on dmenu and the system now thinks your program is dmenu. I can virtually guarantee that those programs are broken now. dmenu works with just X and no terminal.

**Comment by maximbaz** [comment]
Fair point, now `sudo make install` by default installs the binary name as `dmenu-term`, unless you override it with `BIN=xxx`.

I can see you are using AUR package, that one however will remain to install the binary name as `dmenu`, not `dmenu-term`. The AUR package is intended to _replace_ dmenu (hence drop-in replacement), particularly for those who dont use X and need dmenu for apps that use dmenu as an interface.

> It seems you did not think that the two programs could coexist on the same system. 

That's the intention, yes. The PKGBUILD has `conflicts=(dmenu)`, so yes it cannot coexist with anything else that provide `/usr/bin/dmenu`.

> You wipe out the existing dmenu program on installation.

As per above, thanks to `conflicts=(dmenu)`, pacman will prevent installation of `dmenu-term` or any other replacement if you have any other package that provides dmenu binary. So if installation of `dmenu-term` wiped your existing dmenu program, it only means your system was in a bad shape long before that, and pacman had no clue that you already have a dmenu binary.

> In trying to uninstall it I could not simply do "yay -Rns dmenu-term" because there are many dependencies on dmenu and the system now thinks your program is dmenu.

Correct, that is because PKGBUILD contains `provides=(dmenu)`, which literally means it provides dmenu functionality, and all other packages that depend on `dmenu` require _some_ package that provides a dmenu executable. If you want to uninstall `dmenu-term`, you must install some other package that provides dmenu, such as `community/dmenu`.

**Comment by jtgd** [comment]
Does it work with X and without a terminal? If not then it is not a drop in replacement. I could not test that ability because of the aforementioned bug.

**Comment by maximbaz** [comment]
Well it's a script that uses a terminal and a fuzzy filter, both are obviously required to run the script 😄 

I'm not sure where you are trying to lead with the definitions of a drop-in replacements, if you want to use an app, you must install its dependencies, and then you use the app.

**Comment by jtgd** [comment]
The problem is that it only runs with a terminal. I often, if not mostly, run dmenu not within a shell script. If it doesn't run without a terminal then it's clearly not a "drop in replacement" and should not be promoted as such. If it was named something other than dmenu then it's fine. I was expecting something like tmenu, and it's useful to have such a program, but wiping out the real dmenu was a mistake in my opinion. Broke my system and I had to reinstall dmenu to get it back.

The default should be to install as dmenu-term and those who want to can rename it dmenu.

**Comment by maximbaz** [comment]
I also often run dmenu not within a shell script! And in that case this script spawns a new terminal window in the middle of the screen with fuzzy filter inside. A random observer wouldn't even know if this new window is rendered by kitty and not by the application itself 😉 Sorry I still don't get why it matters what internals are used to draw a window on a screen.

I'm glad that you managed to reinstall dmenu to get things back under control. As mentioned previously, when pacman is aware of another dmenu implementation, it wouldn't just blindly override an executable.

This is what is supposed to happen:

```
$ sudo pacman -S dmenu-term
resolving dependencies...
looking for conflicting packages...
:: dmenu-term and dmenu are in conflict. Remove dmenu? [y/N] y

Package (2)          Old Version  New Version  Net Change

dmenu                4.9-1                      -0.08 MiB
maximbaz/dmenu-term               1.0.0-1        0.00 MiB

Total Installed Size:   0.00 MiB
Net Upgrade Size:      -0.08 MiB
```

If the problem is that yay doesnt do it, report it to them please 🙂

**Comment by maximbaz** [comment]
Here's a screencast, just in case my textual description is not clear. In neomutt I click on a link, dmenu appears with selection of what to do with the link, and I press Enter to open it in a browser:

![record_1590011336](https://user-images.githubusercontent.com/1177900/82500993-c7065480-9af4-11ea-8a9b-627a30cb8810.gif)

**Comment by jtgd** [comment]
Thank you for your contributions to open source.
